#pragma once
#include <QString>
#include <QJsonObject>
#include <QJsonDocument>
#include <QDebug>
#include <QtWidgets>
#include <QTimer>

#define NO_ET true


void JSON_read();
void JSON_create();

typedef enum {
    OTHER_SIGNAL_WITH_DATA,

    EYE_TRACKER_INIT,
    EYE_TRACKER_SUCESSFULL_INIT,
    EYE_TRACKER_FAILED_INIT,
    EYE_TRACKER_START_CALIBRATION,
    EYE_TRACKER_SUCESSFULL_CALIBRATION_START,
    EYE_TRACKER_FAILED_CALIBRATION,
    EYE_TRACKER_POINT_TO_CALIBRATE,
    EYE_TRACKER_COMPUTING_AND_APPLYING_CALIBRATION,
    EYE_TRACKER_COMPUTING_AND_APPLYING_CALIBRATION_COMPLETED,
    EYE_TRACKER_LEAVE_CALIBRATION_MODE,

    MENU_ADD_EYE_TRACKER_ACTIONS,
    MENU_OPEN_EYE_TRACKER_CALIBRATION_WIDGET,
    MENU_START_CALIBRATION,

    CONTROLLER_ALL_GADGETS_SUCESSFULL_INITED,
    CONTROLLER_CALIBRATION_WIDGET_CLICKED_START,

    VIEW_CALIBRATION_WIDGET_READY,
    VIEW_INIT_COMRLETED,

    MODEL_INIT_ALL_GADGETS
}ResponseAnswer_ENUM;

Q_DECLARE_METATYPE(ResponseAnswer_ENUM)
